server:
  port: 8082

spring:
  application:
    name: inventory-service

  data:
    mongodb:
      uri: mongodb://admin:Mongo%402024@localhost:27017/intellops_inventory?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

grpc:
  server:
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.intellops: DEBUG
    net.devh: DEBUG
